<a href="https://colab.research.google.com/github/Gopal-krushna-maharana2004/codomax/blob/main/TASK_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK-*3*  || NumPy Fundamentals**

---



Install and Import NumPy


In [5]:
# NumPy is already installed in Google Colab
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


Create NumPy Arrays

In [6]:
# Creating 1D Arrays

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 4, 3, 2, 1])

print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [10 20 30 40 50]
Array 2: [5 4 3 2 1]


Array Properties

In [7]:
print("Shape:", arr1.shape)
print("Dimension:", arr1.ndim)
print("Size:", arr1.size)
print("Datatype:", arr1.dtype)

Shape: (5,)
Dimension: 1
Size: 5
Datatype: int64


Mathematical Operations

In [8]:
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [15 24 33 42 51]
Subtraction: [ 5 16 27 38 49]
Multiplication: [50 80 90 80 50]
Division: [ 2.  5. 10. 20. 50.]


Statistical Functions

In [9]:
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Maximum:", np.max(arr1))
print("Minimum:", np.min(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10
Median: 30.0
Standard Deviation: 14.142135623730951


Create 2D Array

In [10]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Reshape Array

In [11]:
numbers = np.arange(1,13)

print("Original Array")
print(numbers)

reshaped = numbers.reshape(3,4)

print("\nReshaped Array")
print(reshaped)

Original Array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Indexing and Slicing

In [12]:
print("First Element:", arr1[0])
print("Last Element:", arr1[-1])
print("Slice:", arr1[1:4])

print("\nMatrix Element:", matrix[1,2])
print("Second Row:", matrix[1])
print("First Column:", matrix[:,0])

First Element: 10
Last Element: 50
Slice: [20 30 40]

Matrix Element: 6
Second Row: [4 5 6]
First Column: [1 4 7]


Universal Functions

In [13]:
print("Square Root")
print(np.sqrt(arr1))

print("\nSquare")
print(np.square(arr1))

print("\nExponential")
print(np.exp(arr2))

Square Root
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

Square
[ 100  400  900 1600 2500]

Exponential
[148.4131591   54.59815003  20.08553692   7.3890561    2.71828183]


Matrix Operations

In [14]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Matrix A")
print(A)

print("\nMatrix B")
print(B)

print("\nAddition")
print(A+B)

print("\nSubtraction")
print(A-B)

print("\nMatrix Multiplication")
print(np.matmul(A,B))

Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]

Addition
[[ 6  8]
 [10 12]]

Subtraction
[[-4 -4]
 [-4 -4]]

Matrix Multiplication
[[19 22]
 [43 50]]


Random Numbers

In [15]:
random_array = np.random.randint(1,100,(3,3))

print(random_array)

[[45 36 27]
 [87 65 68]
 [11 23 93]]


Mini Practice Task (Marks Analysis)

In [16]:
marks = np.array([85, 90, 78, 92, 88])

print("Student Marks:", marks)

print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Average:", np.mean(marks))
print("Total:", np.sum(marks))

Student Marks: [85 90 78 92 88]
Highest: 92
Lowest: 78
Average: 86.6
Total: 433


Final Section

In [17]:
print("="*50)
print("Day 3 Task Completed Successfully")
print("NumPy Fundamentals Learned")
print("Organization : Codomax Digital Solutions")
print("="*50)

Day 3 Task Completed Successfully
NumPy Fundamentals Learned
Organization : Codomax Digital Solutions
